# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import superglue_pb2 as superglue__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in superglue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuperglueServiceStub:
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/superglue.SuperglueService/Complete',
                request_serializer=superglue__pb2.CompletionRequest.SerializeToString,
                response_deserializer=superglue__pb2.CompletionOutcome.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/superglue.SuperglueService/Stream',
                request_serializer=superglue__pb2.CompletionRequest.SerializeToString,
                response_deserializer=superglue__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.CompleteResponses = channel.unary_unary(
                '/superglue.SuperglueService/CompleteResponses',
                request_serializer=superglue__pb2.ResponsesRequest.SerializeToString,
                response_deserializer=superglue__pb2.ResponsesOutcome.FromString,
                _registered_method=True)
        self.StreamResponses = channel.unary_stream(
                '/superglue.SuperglueService/StreamResponses',
                request_serializer=superglue__pb2.ResponsesRequest.SerializeToString,
                response_deserializer=superglue__pb2.StreamChunk.FromString,
                _registered_method=True)


class SuperglueServiceServicer:
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    def Complete(self, request, context):
        """/ Non-streaming completion with optional tool loop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """/ Server-streaming completion; yields StreamChunk deltas then a final chunk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteResponses(self, request, context):
        """/ Non-streaming Responses API with optional tool loop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamResponses(self, request, context):
        """/ Server-streaming Responses API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperglueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=superglue__pb2.CompletionRequest.FromString,
                    response_serializer=superglue__pb2.CompletionOutcome.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=superglue__pb2.CompletionRequest.FromString,
                    response_serializer=superglue__pb2.StreamChunk.SerializeToString,
            ),
            'CompleteResponses': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteResponses,
                    request_deserializer=superglue__pb2.ResponsesRequest.FromString,
                    response_serializer=superglue__pb2.ResponsesOutcome.SerializeToString,
            ),
            'StreamResponses': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamResponses,
                    request_deserializer=superglue__pb2.ResponsesRequest.FromString,
                    response_serializer=superglue__pb2.StreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'superglue.SuperglueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('superglue.SuperglueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuperglueService:
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/superglue.SuperglueService/Complete',
            superglue__pb2.CompletionRequest.SerializeToString,
            superglue__pb2.CompletionOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/superglue.SuperglueService/Stream',
            superglue__pb2.CompletionRequest.SerializeToString,
            superglue__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteResponses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/superglue.SuperglueService/CompleteResponses',
            superglue__pb2.ResponsesRequest.SerializeToString,
            superglue__pb2.ResponsesOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamResponses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/superglue.SuperglueService/StreamResponses',
            superglue__pb2.ResponsesRequest.SerializeToString,
            superglue__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
