/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AgentEngine {
  constructor(spec: AgentSpecJs, apiKey: string, baseUrl?: string | undefined | null, model?: string | undefined | null, maxRetries?: number | undefined | null, retryInitialDelayMs?: number | undefined | null, retryMaxDelayMs?: number | undefined | null, retryMultiplier?: number | undefined | null, requestsPerSecond?: number | undefined | null, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, poolMaxIdlePerHost?: number | undefined | null, poolIdleTimeoutSecs?: number | undefined | null, reasoningEffort?: string | undefined | null, statusEmitter?: StatusEmitterJs | undefined | null)
  registerTool(name: string, description: string, parameters: any, callback: JsonCallback): Promise<void>
  registerHook(stage: string, handler: JsonCallback, name?: string | undefined | null, errorStrategy?: string | undefined | null): Promise<void>
  registerGuardrail(handler: GuardrailCallback, stage?: string | undefined | null, name?: string | undefined | null): Promise<void>
  run(userMessage: string, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null): Promise<CompletionOutcomeJs>
  stream(userMessage: string, onToken: ((err: Error | null, arg: string) => void), timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null): Promise<StreamOutcomeJs>
}
export type JsAgentEngine = AgentEngine

export declare class AgentSpecJs {
  constructor(name: string, persona: string, goals: Array<string> | undefined | null, constraints: Array<string> | undefined | null, model: string, maxToolRounds: number, maxOutputRetries: number, systemPrompt?: string | undefined | null, reasoningEffort?: string | undefined | null)
  get name(): string
  get persona(): string
  get goals(): Array<string>
  get constraints(): Array<string>
  get model(): string
  get maxToolRounds(): number
  get maxOutputRetries(): number
  get reasoningEffort(): string | null
  compileSystemPrompt(): string
}

export declare class Client {
  constructor(apiKey: string, model?: string | undefined, baseUrl?: string | undefined, systemPrompt?: string | undefined | null, maxToolRounds?: number | undefined | null, maxRetries?: number | undefined | null, retryInitialDelayMs?: number | undefined | null, retryMaxDelayMs?: number | undefined | null, retryMultiplier?: number | undefined | null, requestsPerSecond?: number | undefined | null, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, maxOutputRetries?: number | undefined | null, poolMaxIdlePerHost?: number | undefined | null, poolIdleTimeoutSecs?: number | undefined | null, reasoningEffort?: string | undefined | null, statusEmitter?: StatusEmitterJs | undefined | null, modelFallbackModels?: Array<string> | undefined | null, apiKeys?: Record<string, string> | undefined | null, requestsPerSecondFor?: Record<string, number> | undefined | null, maxUploadBytes?: number | undefined | null)
  uploadFile(path: string, purpose?: string | undefined | null, provider?: string | undefined | null): Promise<UploadedFileJs>
  static messageWithFileBytes(filename: string, fileBytes: Buffer, text?: string | undefined | null): any
  /** Register a tool: `callback` receives JSON args and returns a JSON object (or Promise of). */
  registerTool(name: string, description: string, parameters: any, callback: JsonCallback): Promise<void>
  registerHook(stage: string, handler: JsonCallback, name?: string | undefined, errorStrategy?: string | undefined | null): Promise<void>
  registerGuardrail(handler: GuardrailCallback, stage?: string | undefined | null, name?: string | undefined | null): Promise<void>
  addBlocklistGuardrail(patterns: Array<string>, action?: string | undefined | null, stage?: string | undefined | null, name?: string | undefined | null): Promise<void>
  addMaxLengthGuardrail(maxInput?: number | undefined | null, maxOutput?: number | undefined | null, strategy?: string | undefined | null, name?: string | undefined | null): Promise<void>
  addPiiGuardrail(stage?: string | undefined | null, name?: string | undefined | null): Promise<void>
  runAgent(spec: AgentSpecJs, userMessage: string, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null): Promise<CompletionOutcomeJs>
  complete(userMessage: string, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<CompletionOutcomeJs>
  /** gluellm-compatible alias for [`Client::complete`]. */
  response(userMessage: string, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<CompletionOutcomeJs>
  completeMessages(messages: any, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<CompletionOutcomeJs>
  stream(userMessage: string, onToken: ((err: Error | null, arg: string) => void), timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<StreamOutcomeJs>
  completeResponse(userMessage: string, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<ResponseOutcomeJs>
  streamResponse(userMessage: string, onToken: ((err: Error | null, arg: string) => void), timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null): Promise<ResponseStreamOutcomeJs>
  connectMcpStdio(command: string, args?: Array<string> | undefined | null, env?: Record<string, string> | undefined | null, prefix?: string | undefined | null): Promise<void>
  connectMcpHttp(url: string, prefix?: string | undefined | null): Promise<void>
  batch(requests: Array<BatchRequestJs>, maxConcurrent?: number | undefined | null, errorStrategy?: string | undefined | null, timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null): Promise<BatchResponseJs>
}

export declare class Conversation {
  constructor(client: Client)
  pushUser(text: string): void
  pushAssistantText(text: string): void
  get messages(): any
  complete(timeoutSecs?: number | undefined | null, connectTimeoutSecs?: number | undefined | null, requestId?: string | undefined | null, reasoningEffort?: string | undefined | null): Promise<CompletionOutcomeJs>
}

export declare class StatusEmitterJs {
  constructor()
  subscribe(callback: StatusCallback): void
}

export interface BatchRequestJs {
  prompt: string
  id?: string
  systemPrompt?: string
}

export interface BatchResponseJs {
  results: Array<BatchResultJs>
  totalRequests: number
  successful: number
  failed: number
  elapsedSecs: number
  totalUsage?: any
}

export interface BatchResultJs {
  id: string
  success: boolean
  content?: string
  error?: string
  rounds: number
  usage?: any
  elapsedSecs: number
}

export interface CompletionOutcomeJs {
  content?: string
  rounds: number
  usage?: any
  requestId: string
  modelUsed: string
  messages: any
}

export interface ResponseOutcomeJs {
  id: string
  content?: string
  rounds: number
  usage?: any
  requestId: string
  modelUsed: string
}

export interface ResponseStreamOutcomeJs {
  id: string
  content: string
  usage?: any
  requestId: string
  modelUsed: string
}

export interface StreamOutcomeJs {
  content: string
  finishReason?: string
  usage?: any
  requestId: string
}

export interface UploadedFileJs {
  provider: string
  fileId: string
  filename: string
  bytes: number
  purpose: string
}

export declare function version(): string
